version: '3.8'

services:
  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pokemon_app
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
      - ./src/vendor:/var/www/html/vendor
    networks:
      - pokemon-network
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=pokemon_db
      - DB_USERNAME=db_user
      - DB_PASSWORD=db_password

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: pokemon_webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - pokemon-network
    depends_on:
      - app

  # MySQL Service
  db:
    image: mysql:5.7
    container_name: pokemon_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: pokemon_db
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pokemon-network
    ports:
      - "3306:3306"

# Docker Networks
networks:
  pokemon-network:
    driver: bridge

# Volumes
volumes:
  db_data:
    driver: local